@echo off
echo [ExamPilot AI] Initializing Git Repository...
git init
echo [ExamPilot AI] Adding remote origin...
git remote add origin https://github.com/MounikaDongari16/eamcet.git
echo [ExamPilot AI] Adding files...
git add .
echo [ExamPilot AI] Committing changes...
git commit -m "Initial commit: ExamPilot AI - Real-Time Learning Navigator"
echo [ExamPilot AI] Setting branch name...
git branch -M main
echo [ExamPilot AI] Pushing to GitHub...
git push -u origin main
echo [ExamPilot AI] Done! Please check your repository.
pause
